import { Joya } from '../models/joya.model';

export const joyas: Joya[] = [
    {
        nombre: "Aretes_001",
        descripcion: "Arete corazón XL y perla (Plata bañado en oro).",
        img: "assets/img/arete_001.png",
        materiales: "plata bañada en oro",
        tamanio: "1.5 cm",
        precio: 79.00,

      },
      {
        nombre: "Aretes_002",
        descripcion: "Arete copo de nieve multicolor (plata bañado en oro).",
        img: "assets/img/arete_002.png",
        materiales: "plata bañada en oro",
        tamanio: "0.8 cm de circunferencia",
        precio: 59.00,
      },
      {
        nombre: "Aretes_003",
        descripcion: "Arete Perla Dona (Plata bañado en oro).",
        img: "assets/img/arete_003.png",
        materiales: "plata bañada en oro",
        tamanio: "0.7 cm",
        precio: 69.00,
      },
      {
        nombre: "Aretes_004",
        descripcion: "Arete libélula lisa (Plata Pura).",
        img: "assets/img/arete_004.png",
        materiales: "plata bañada en oro",
        tamanio: "0.5 cm",
        precio: 49.00,
      },
      {
        nombre: "Aretes_005",
        descripcion: "Arete estrella multicolor XL.",
        img: "assets/img/arete_005.png",
        materiales: "cobre enchapado en oro",
        tamanio: "",
        precio: 45.00,
      },
      
      
      {        nombre: "anillo_001",
        descripcion: "Anillo corazón calado pequeño (plata bañado en oro).",
        img: "assets/img/anillo_001.png",
        materiales: "plata bañada en oro",
        tamanio: "16 cm de diámetro",
        precio: 79.00,
      },
      {
        nombre: "anillo_002",
        descripcion: "Anillo cruzado punto luz (Plata bañado en oro).",
        img: "assets/img/anillo_002.png",
        materiales: "plata bañada en oro",
        tamanio: "autoregulable",
        precio: 89.00,
      },
      {
        nombre: "anillo_003",
        descripcion: "Anillo doble con tres flores strass (plata bañado en oro).",
        img: "assets/img/anillo_003.png",
        materiales: "plata bañada en oro",
        tamanio: "regulable",
        precio: 109.00,
      },
      {
        nombre: "anillo_004",
        descripcion: "Anillo cadena cubo punto luz (plata bañado en oro).",
        img: "assets/img/anillo_004.png",
        materiales: "plata bañada en oro",
        tamanio: "Talla 6 - (1.6 cm. de diámetro)",
        precio: 99.00,
      },
      {
        nombre: "anillo_005",
        descripcion: "Anillo corazón calado (plata bañado en oro).",
        img: "assets/img/anillo_005.png",
        materiales: "plata bañada en oro",
        tamanio: "19 cm de diámetro",
        precio: 79.00,
      },
      {
        nombre: "Pulsera_001",
        descripcion: "Brazalete acero media caña ovalado.",
        img: "assets/img/pulsera_001.png",
        materiales: "Acero quirúrgico",
        tamanio: "6.4 cm",
        precio: 69.00,
      },
      {
        nombre: "Pulsera_002",
        descripcion: "Pulsera sole cadena placa y estrella.",
        img: "assets/img/pulsera_002.png",
        materiales: "cobre enchapadode oro",
        tamanio: "19.5 cm. aprox",
        precio: 69.00,
      },
      {
        nombre: "Pulsera_003",
        descripcion: "pulsera sole hilo niño y niña strass.",
        img: "assets/img/pulsera_003.png",
        materiales: "cobre enchapadode oro con inscrutes de cristales",
        tamanio: "19.5 cm. aprox",
        precio: 75.00,
      },
      {
        nombre: "Pulsera_004",
        descripcion: "pulsera Zoe azul ojo rasgado borde turquesa.",
        img: "assets/img/pulsera_004.png",
        materiales: "Hilo hindú, chaquiras de acero y dije de cobre enchpado en oro",
        tamanio: "Regulable",
        precio: 65.00,
      },
      {
        nombre: "Pulsera_005",
        descripcion: "Pulsera Vera hilo huellita.",
        img: "assets/img/pulsera_005.png",
        materiales: "hilo hindú, muranos y dije de acero quierúrgico",
        tamanio: "autoregulable",
        precio: 49.00,
      },
];